#!/bin/bash
src_dir="$(dirname "$0")"
"$src_dir/common.sh"

ssh -t -i $(terraform output bastion.private_key_path) "$(terraform output nat.user)@$(terraform output nat.ip)" sudo docker run --volumes-from ovpn-data --rm -it gosuri/openvpn easyrsa build-client-full "${1}" nopass
